export const EXPENSES_FAILED = 'EXPENSES_FAILED';
export const EXPENSES_FAILED_CREATED = 'EXPENSES_FAILED_CREATED';
export const EXPENSES_RECEIVED = 'EXPENSES_RECEIVED';
export const EXPENSES_RECEIVED_CREATED = 'EXPENSES_RECEIVED_CREATED';
export const EXPENSES_REQUESTED = 'EXPENSES_REQUESTED';
export const EXPENSES_REQUESTED_CREATED = 'EXPENSES_REQUESTED_CREATED';
