export const EXPENSES_FAILED_INDEX = 'EXPENSES_FAILED_INDEX';
export const EXPENSES_FAILED_CREATE = 'EXPENSES_FAILED_CREATE';
export const EXPENSES_FAILED_DELETE = 'EXPENSES_FAILED_DELETE';
export const EXPENSES_FAILED_UPDATE = 'EXPENSES_FAILED_UPDATE';

export const EXPENSES_RECEIVED_INDEX = 'EXPENSES_RECEIVED_INDEX';
export const EXPENSES_RECEIVED_CREATE = 'EXPENSES_RECEIVED_CREATE';
export const EXPENSES_RECEIVED_DELETE = 'EXPENSES_RECEIVED_DELETE';
export const EXPENSES_RECEIVED_UPDATE = 'EXPENSES_RECEIVED_UPDATE';

export const EXPENSES_REQUESTED_INDEX = 'EXPENSES_REQUESTED_INDEX';
export const EXPENSES_REQUESTED_CREATE = 'EXPENSES_REQUESTED_CREATE';
export const EXPENSES_REQUESTED_DELETE = 'EXPENSES_REQUESTED_DELETE';
export const EXPENSES_REQUESTED_UPDATE = 'EXPENSES_REQUESTED_UPDATE';

export const EXPENSES_UPDATED = 'EXPENSES_UPDATED';
