export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_VALUE_CHANGED = 'LOGIN_VALUE_CHANGED';
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED';
