export const LOCAL_STORAGE_KEY_SESSION = 'SESSION';
export const LOCAL_STORAGE_KEY_TIMER_ACTIVE = 'TIMER_ACTIVE';
export const LOCAL_STORAGE_KEY_TIMER_END = 'TIMER_END';
export const LOCAL_STORAGE_KEY_TIMER_START = 'TIMER_START';
export const LOCAL_STORAGE_KEY_USER = 'USER';
export const OFFLINE_MODE = false;
